name: Issue metrics
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: read

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          first_day="2020-05-01"
          last_day=$(date -d "today" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "$first_day..$last_day"
          echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:darthcloud/BlueRetro created:${{ env.last_month }}'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: issue_metrics
          path: |
            issue_metrics.md
          if-no-files-found: error